### PR TITLE
Teabagged

### PR DESCRIPTION
**Pull request by jejacks0n**
I wanted to get some stuff sorted with teabag -- this allowed me to identify the issues that are still lingering and address.

This branch makes all the changes needed for Teabag, includes some cleanup, and has all tests passing in the browser (chrome).  I'll need to do some investigation about phantomjs and why "focus" isn't working for 4 remaining failures when running the `rake teabag` task.

### CODE REVIEW

**Comment by mkitt** [comment]
Couple of things before merging in...
1. All tests are passing in the browser, but there are failures when running from the CLI runner.
2. The "passes" text is showing: 5288 (in the browser reporter), the CLI runner looks like it is reporting the correct number of tests. I think there is something like 526 tests or something.
3. The `#teabag-fixtures` are showing through on top of the test runner. Any way to move this to a lower `z-index` or something so you don't see it?
4. The test runner in the browser is quite a bit slower (23 seconds) than the Jasmine runner (4 seconds), any way to speed this up?

Thanks for hopping on this, stoked to get this in! Also no rush on this, as I'm probably not going to do a whole lot of work on utensils over the break and you shouldn't either.

**Comment by jejacks0n** [comment]
Cool, thanks for checking it out!

I'd say you need to restart the server after bundling.. you're seeing what it looked like before I fixed some things in Teabag -- but only in the browser -- which to me reads as you don't have the most recent code running.

That should take care of 2, and 4.
1. Yeah, there's just the specs that are asserting focus that are failing, which I'll have to look into -- but since this isn't running on CI it seems like it's ok to pull in?
2. I have a hard time with this.. from my perspective the fixture element should be positioned absolutely at 0x0 -- which helps when you're doing positional math and doesn't impact much if you're not.. it's visible because that can be useful when you throw a debugger line in the javascript -- you can actually see what's going on which can be invaluable for inspecting elements etc. Thoughts?

**Comment by mkitt** [comment]
Merging this in.. thanks!

**Comment by jejacks0n** [comment]
haha, I was just working on this to improve it.

**Comment by jejacks0n** [comment]
I'm doing some more with the specs -- on master.

**Comment by mkitt** [comment]
Sweet.. it was working enough for me to bring it over to master so yeah go nuts. We probably should move over to Teabags's fixtures too, but I'm in no rush. thanks man.. it's way nicer!

**Pull request merged**
